debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    org.org.capstone.maru: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: false
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0d7c948d8eaadc0e08f3e42636bba3bd
            clientSecret: bIH2tF6jMbrRsdAp9DPL7yh97LP8pPXk
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
          naver:
            client-id: OvLyXvoT1NlEr8Wfiu2u
            client-secret: U6Or_rMFOQ
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/auth
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
