debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    org.org.capstone.maru: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  jpa:
    database: postgresql
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: false
        order_updates: true
        jdbc:
          batch_versioned_data: true
  profiles:
    include:
      - oauth
      - datasource
      - cloud
      - redis

jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 100

univcert:
  api_key: 91927da3-bc95-4574-8d43-47e10a9272a7

server:
  tomcat:
    keep-alive-timeout: 300000
